#pragma once

#include <stdint.h>

namespace common::constants
{

const uint16_t LAYER_HOLD_MODIFIER = 0xC000;
const uint16_t LAYER_TOGGLE_MODIFIER = 0xB000;
const uint16_t MOUSE_BASE_CODE = 0xA000;
const uint16_t CONTROL_BASE_CODE = 0xD000;

const uint16_t LAYER_HOLD_1 = (130 | LAYER_HOLD_MODIFIER);
const uint16_t LAYER_HOLD_2 = (131 | LAYER_HOLD_MODIFIER);

const uint16_t LAYER_TOGGLE_1 = (133 | LAYER_TOGGLE_MODIFIER);
const uint16_t LAYER_TOGGLE_2 = (134 | LAYER_TOGGLE_MODIFIER);

const uint16_t MOUSE_LEFT_CLICK =       (116 | MOUSE_BASE_CODE);
const uint16_t MOUSE_RIGHT_CLICK =      (117 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MIDDLE_CLICK =     (118 | MOUSE_BASE_CODE);
const uint16_t MOUSE_SCROLL_UP =        (119 | MOUSE_BASE_CODE);
const uint16_t MOUSE_SCROLL_DOWN =      (120 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MOVE_LEFT =        (121 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MOVE_RIGHT =       (122 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MOVE_UP =          (123 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MOVE_DOWN =        (124 | MOUSE_BASE_CODE);
const uint16_t MOUSE_MOVE_ACCELERATE =  (125 | MOUSE_BASE_CODE);
const uint16_t MAX_MOUSE_CODE = 125;

const uint16_t CONTROL_BRIGHTNESS_INC =      (126 | CONTROL_BASE_CODE);
const uint16_t CONTROL_BRIGHTNESS_DEC =      (127 | CONTROL_BASE_CODE);
const uint16_t CONTROL_CONFIG_MODE_TOGGLE =  (128 | CONTROL_BASE_CODE);
const uint16_t CONTROL_NEXT_BACKLIGHT_MODE = (129 | CONTROL_BASE_CODE);
const uint16_t MAX_CONTROL_CODE = 129;

}
